/**
 * Shared types for the journey-map view component.
 *
 * Same shape as the artifact JSON in
 *   src/lib/content/corpora/<corpus_id>/artifacts/journey-map-<persona_id>.json
 * generated by scripts/synthesize-journey-map.mjs.
 */

export type Observation = {
	title: string;
	polarity: 'positive' | 'negative' | 'mixed';
	body: string;
	supporting_fragment_ids: string[];
	confidence: number;
};

export type ExternalObservation = {
	title: string;
	body: string;
	citation?: string;
	source_dataset_ids?: string[];
	confidence?: number;
	source_url?: string;
};

export type StepMap = {
	step_id: string | null;
	label: string | null;
	observations: Observation[];
	external_observations: ExternalObservation[];
};

export type StageMap = {
	stage_id: string;
	label: string;
	description: string;
	fragment_count: number;
	avg_sentiment: number | null;
	emotion_label: string | null;
	stage_summary: string;
	drill_down: { text: string; supporting_fragment_ids: string[] } | null;
	steps: StepMap[];
};

export type DecisionPanelItem = {
	title: string;
	body: string;
	supporting_fragment_ids: string[];
	confidence: number;
};

export type DecisionPanel = {
	stage_id: string;
	label: string;
	drivers: DecisionPanelItem[];
	barriers: DecisionPanelItem[];
	mixed: DecisionPanelItem[];
};

export type ExternalObservationsProposerMeta = {
	generator: string;
	generator_version: string;
	model: string;
	generated_at: string;
	datasets_consumed: string[];
	count: number;
};

export type JourneyMapArtifact = {
	meta: {
		schema_version: string;
		corpus_id: string;
		persona_id: string;
		persona_label: string;
		persona_color: string | null;
		journey_indication: string;
		generated_at: string;
		generator: string;
		model: string;
		fragment_count_total: number;
		stage_count: number;
		decision_point_count: number;
		notes: string[];
		external_observations_proposer?: ExternalObservationsProposerMeta;
	};
	stages: StageMap[];
	decision_panels: DecisionPanel[];
};
